spring.application.name=fitness-monolith

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PAS}

spring.jpa.hibernate.ddl-auto=update
jwt.secret=${DB_SECRET}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG